# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pantalla_inicio.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PantallaInicio(object):
    def setupUi(self, PantallaInicio):
        PantallaInicio.setObjectName("PantallaInicio")
        PantallaInicio.resize(1014, 682)
        self.horizontalLayoutWidget = QtWidgets.QWidget(PantallaInicio)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 981, 654))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label_nombre_usuario = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(14)
        self.label_nombre_usuario.setFont(font)
        self.label_nombre_usuario.setObjectName("label_nombre_usuario")
        self.verticalLayout.addWidget(self.label_nombre_usuario)
        self.label_puntaje = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_puntaje.setFont(font)
        self.label_puntaje.setObjectName("label_puntaje")
        self.verticalLayout.addWidget(self.label_puntaje)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 179, 57))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 179, 57))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.label_2.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(36)
        self.label_2.setFont(font)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setTextFormat(QtCore.Qt.PlainText)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_3.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(72)
        self.label_3.setFont(font)
        self.label_3.setTextFormat(QtCore.Qt.PlainText)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.layout_salas_normales = QtWidgets.QVBoxLayout()
        self.layout_salas_normales.setObjectName("layout_salas_normales")
        self.label_10 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.layout_salas_normales.addWidget(self.label_10)
        self.label_s1 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_s1.setText("")
        self.label_s1.setObjectName("label_s1")
        self.layout_salas_normales.addWidget(self.label_s1)
        self.pushButton_s1 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_s1.setEnabled(True)
        self.pushButton_s1.setObjectName("pushButton_s1")
        self.layout_salas_normales.addWidget(self.pushButton_s1)
        self.label_s2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_s2.setText("")
        self.label_s2.setObjectName("label_s2")
        self.layout_salas_normales.addWidget(self.label_s2)
        self.pushButton_s2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_s2.setObjectName("pushButton_s2")
        self.layout_salas_normales.addWidget(self.pushButton_s2)
        self.label_s3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_s3.setText("")
        self.label_s3.setObjectName("label_s3")
        self.layout_salas_normales.addWidget(self.label_s3)
        self.pushButton_s3 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_s3.setObjectName("pushButton_s3")
        self.layout_salas_normales.addWidget(self.pushButton_s3)
        self.label_s4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_s4.setText("")
        self.label_s4.setObjectName("label_s4")
        self.layout_salas_normales.addWidget(self.label_s4)
        self.pushButton_s4 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_s4.setObjectName("pushButton_s4")
        self.layout_salas_normales.addWidget(self.pushButton_s4)
        self.label_s5 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_s5.setText("")
        self.label_s5.setObjectName("label_s5")
        self.layout_salas_normales.addWidget(self.label_s5)
        self.pushButton_s5 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_s5.setObjectName("pushButton_s5")
        self.layout_salas_normales.addWidget(self.pushButton_s5)
        self.label_s6 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_s6.setText("")
        self.label_s6.setObjectName("label_s6")
        self.layout_salas_normales.addWidget(self.label_s6)
        self.pushButton_s6 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_s6.setObjectName("pushButton_s6")
        self.layout_salas_normales.addWidget(self.pushButton_s6)
        self.horizontalLayout.addLayout(self.layout_salas_normales)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_11 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_3.addWidget(self.label_11)
        self.label_e1 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_e1.setText("")
        self.label_e1.setObjectName("label_e1")
        self.verticalLayout_3.addWidget(self.label_e1)
        self.pushButton_e1 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_e1.setEnabled(True)
        self.pushButton_e1.setObjectName("pushButton_e1")
        self.verticalLayout_3.addWidget(self.pushButton_e1)
        self.label_e2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_e2.setText("")
        self.label_e2.setObjectName("label_e2")
        self.verticalLayout_3.addWidget(self.label_e2)
        self.pushButton_e2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_e2.setEnabled(True)
        self.pushButton_e2.setObjectName("pushButton_e2")
        self.verticalLayout_3.addWidget(self.pushButton_e2)
        self.label_e3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_e3.setText("")
        self.label_e3.setObjectName("label_e3")
        self.verticalLayout_3.addWidget(self.label_e3)
        self.pushButton_e3 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_e3.setEnabled(True)
        self.pushButton_e3.setObjectName("pushButton_e3")
        self.verticalLayout_3.addWidget(self.pushButton_e3)
        self.label_e4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_e4.setText("")
        self.label_e4.setObjectName("label_e4")
        self.verticalLayout_3.addWidget(self.label_e4)
        self.pushButton_e4 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_e4.setEnabled(True)
        self.pushButton_e4.setObjectName("pushButton_e4")
        self.verticalLayout_3.addWidget(self.pushButton_e4)
        self.label_e5 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_e5.setText("")
        self.label_e5.setObjectName("label_e5")
        self.verticalLayout_3.addWidget(self.label_e5)
        self.pushButton_e5 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_e5.setEnabled(True)
        self.pushButton_e5.setObjectName("pushButton_e5")
        self.verticalLayout_3.addWidget(self.pushButton_e5)
        self.label_e6 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_e6.setText("")
        self.label_e6.setObjectName("label_e6")
        self.verticalLayout_3.addWidget(self.label_e6)
        self.pushButton_e6 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_e6.setEnabled(True)
        self.pushButton_e6.setObjectName("pushButton_e6")
        self.verticalLayout_3.addWidget(self.pushButton_e6)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_12 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_2.addWidget(self.label_12)
        self.label_21 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_21.setText("")
        self.label_21.setObjectName("label_21")
        self.verticalLayout_2.addWidget(self.label_21)
        self.pushButton_21 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_21.setEnabled(True)
        self.pushButton_21.setObjectName("pushButton_21")
        self.verticalLayout_2.addWidget(self.pushButton_21)
        self.label_22 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_22.setText("")
        self.label_22.setObjectName("label_22")
        self.verticalLayout_2.addWidget(self.label_22)
        self.pushButton_22 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_22.setEnabled(True)
        self.pushButton_22.setObjectName("pushButton_22")
        self.verticalLayout_2.addWidget(self.pushButton_22)
        self.label_23 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_23.setText("")
        self.label_23.setObjectName("label_23")
        self.verticalLayout_2.addWidget(self.label_23)
        self.pushButton_23 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_23.setEnabled(True)
        self.pushButton_23.setObjectName("pushButton_23")
        self.verticalLayout_2.addWidget(self.pushButton_23)
        self.label_24 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_24.setText("")
        self.label_24.setObjectName("label_24")
        self.verticalLayout_2.addWidget(self.label_24)
        self.pushButton_24 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_24.setEnabled(True)
        self.pushButton_24.setObjectName("pushButton_24")
        self.verticalLayout_2.addWidget(self.pushButton_24)
        self.label_25 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_25.setText("")
        self.label_25.setObjectName("label_25")
        self.verticalLayout_2.addWidget(self.label_25)
        self.pushButton_25 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_25.setEnabled(True)
        self.pushButton_25.setObjectName("pushButton_25")
        self.verticalLayout_2.addWidget(self.pushButton_25)
        self.label_26 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_26.setText("")
        self.label_26.setObjectName("label_26")
        self.verticalLayout_2.addWidget(self.label_26)
        self.pushButton_26 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_26.setEnabled(True)
        self.pushButton_26.setObjectName("pushButton_26")
        self.verticalLayout_2.addWidget(self.pushButton_26)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayoutWidget.raise_()
        self.label_11.raise_()

        self.retranslateUi(PantallaInicio)
        QtCore.QMetaObject.connectSlotsByName(PantallaInicio)

    def retranslateUi(self, PantallaInicio):
        _translate = QtCore.QCoreApplication.translate
        PantallaInicio.setWindowTitle(_translate("PantallaInicio", "PrograPop"))
        self.label_nombre_usuario.setText(_translate("PantallaInicio", "<Nombre Usuario:>"))
        self.label_puntaje.setText(_translate("PantallaInicio", "<Puntaje>"))
        self.label_2.setText(_translate("PantallaInicio", "PROGRA"))
        self.label_3.setText(_translate("PantallaInicio", "POP"))
        self.label_10.setText(_translate("PantallaInicio", "SALAS NORMALES"))
        self.pushButton_s1.setText(_translate("PantallaInicio", "Entrar"))
        self.pushButton_s2.setText(_translate("PantallaInicio", "Entrar"))
        self.pushButton_s3.setText(_translate("PantallaInicio", "Entrar"))
        self.pushButton_s4.setText(_translate("PantallaInicio", "Entrar"))
        self.pushButton_s5.setText(_translate("PantallaInicio", "Entrar"))
        self.pushButton_s6.setText(_translate("PantallaInicio", "Entrar"))
        self.label_11.setText(_translate("PantallaInicio", "SALAS ECUALIZADOR"))
        self.pushButton_e1.setText(_translate("PantallaInicio", "Entrar"))
        self.pushButton_e2.setText(_translate("PantallaInicio", "Entrar"))
        self.pushButton_e3.setText(_translate("PantallaInicio", "Entrar"))
        self.pushButton_e4.setText(_translate("PantallaInicio", "Entrar"))
        self.pushButton_e5.setText(_translate("PantallaInicio", "Entrar"))
        self.pushButton_e6.setText(_translate("PantallaInicio", "Entrar"))
        self.label_12.setText(_translate("PantallaInicio", "SALAS 2x CANCION"))
        self.pushButton_21.setText(_translate("PantallaInicio", "Entrar"))
        self.pushButton_22.setText(_translate("PantallaInicio", "Entrar"))
        self.pushButton_23.setText(_translate("PantallaInicio", "Entrar"))
        self.pushButton_24.setText(_translate("PantallaInicio", "Entrar"))
        self.pushButton_25.setText(_translate("PantallaInicio", "Entrar"))
        self.pushButton_26.setText(_translate("PantallaInicio", "Entrar"))

